# general configuration
url: http://mykoz.github.io
baseurl: ''

# social usernames/URLs
#twitter_username: mykoz
#github_username:  mykoz
#linkedin_link: https://www.linkedin.com/in/mzhang89
#google_plus_link: 
#stackoverflow_link:
# Site owner
owner:
  name: Michael Zhang
  avatar: #bio-photo.jpg
  email: zhang.michael89@gmail.com
  disqus-shortname:
  twitter: mykoz
  facebook: #username
  github: mykoz
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: mzhang89
  instagram: mykoz
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify: 

# compass confilguration
compass:
  # an avatar or logo (optional)
  logo: "/images/compass.png"
  # author will appear under the avatar (optional)
  author: "Navigating Data Science"
  # tagline will appear under the title (optional)
  tagline: "Learn with the flow"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true
